services:
  - type: web
    name: telegram-topic-forwarder
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python forwarder_advanced.py
    envVars:
      - key: API_ID
        value: 35188145
      - key: API_HASH
        value: 3f725a3cf7a87167a58c4e098c9a1828
      - key: BOT_TOKEN
        value: 8695455961:AAFzQOswXeDgkKMbImwI8jDrTd_glAmn39k
      - key: DESTINATION_CHANNEL
        value: "@gatearshadbackup"
      - key: DATABASE
        value: ""
      - key: BOT_OWNER_ID
        value: "0"
